dbtlearn:
  outputs:
    dev:
      account:yba41802.east-us-2.azure # Fill in the Snowflake Account Name here (someting like: yczmxn-dk96978)
      database: AIRBNB
      password: Welcome123$$
      role: transform
      schema: dev
      threads: 1
      type: snowflake
      user: 9632455899
      warehouse: COMPUTE_WH
  target: dev
  
