{% macro get_localized_datepart_names(language, datepart) %}
    {{
        return(
            adapter.dispatch("get_localized_datepart_names", "dbt_date")(
                language, datepart
            )
        )
    }}
{% endmacro %}

{% macro default__get_localized_datepart_names(language, datepart) %}
    {% set datepart_names_by_language = {
        "en": {
            "weekdays": {
                "long": {
                    "1": "Monday",
                    "2": "Tuesday",
                    "3": "Wednesday",
                    "4": "Thursday",
                    "5": "Friday",
                    "6": "Saturday",
                    "7": "Sunday",
                },
                "short": {
                    "1": "Mon",
                    "2": "Tue",
                    "3": "Wed",
                    "4": "Thu",
                    "5": "Fri",
                    "6": "Sat",
                    "7": "Sun",
                },
            },
            "months": {
                "long": {
                    "1": "January",
                    "2": "February",
                    "3": "March",
                    "4": "April",
                    "5": "May",
                    "6": "June",
                    "7": "July",
                    "8": "August",
                    "9": "September",
                    "10": "October",
                    "11": "November",
                    "12": "December",
                },
                "short": {
                    "1": "Jan",
                    "2": "Feb",
                    "3": "Mar",
                    "4": "Apr",
                    "5": "May",
                    "6": "Jun",
                    "7": "Jul",
                    "8": "Aug",
                    "9": "Sep",
                    "10": "Oct",
                    "11": "Nov",
                    "12": "Dec",
                },
            },
            "seasons": {
                "1": "winter",
                "2": "spring",
                "3": "summer",
                "4": "autumn",
            },
        },
        "nl": {
            "weekdays": {
                "long": {
                    "1": "maandag",
                    "2": "dinsdag",
                    "3": "woensdag",
                    "4": "donderdag",
                    "5": "vrijdag",
                    "6": "zaterdag",
                    "7": "zondag",
                },
                "short": {
                    "1": "ma",
                    "2": "di",
                    "3": "wo",
                    "4": "do",
                    "5": "vr",
                    "6": "za",
                    "7": "zo",
                },
            },
            "months": {
                "long": {
                    "1": "januari",
                    "2": "februari",
                    "3": "maart",
                    "4": "april",
                    "5": "mei",
                    "6": "juni",
                    "7": "juli",
                    "8": "augustus",
                    "9": "september",
                    "10": "oktober",
                    "11": "november",
                    "12": "december",
                },
                "short": {
                    "1": "jan",
                    "2": "feb",
                    "3": "mrt",
                    "4": "apr",
                    "5": "mei",
                    "6": "jun",
                    "7": "jul",
                    "8": "aug",
                    "9": "sep",
                    "10": "okt",
                    "11": "nov",
                    "12": "dec",
                },
            },
            "seasons": {
                "1": "winter",
                "2": "lente",
                "3": "zomer",
                "4": "herfst",
            },
        },
        "de": {
            "weekdays": {
                "long": {
                    "1": "Montag",
                    "2": "Dienstag",
                    "3": "Mittwoch",
                    "4": "Donnerstag",
                    "5": "Freitag",
                    "6": "Samstag",
                    "7": "Sonntag",
                },
                "short": {
                    "1": "Mo",
                    "2": "Di",
                    "3": "Mi",
                    "4": "Do",
                    "5": "Fr",
                    "6": "Sa",
                    "7": "So",
                },
            },
            "months": {
                "long": {
                    "1": "Januar",
                    "2": "Februar",
                    "3": "März",
                    "4": "April",
                    "5": "Mai",
                    "6": "Juni",
                    "7": "Juli",
                    "8": "August",
                    "9": "September",
                    "10": "Oktober",
                    "11": "November",
                    "12": "Dezember",
                },
                "short": {
                    "1": "Jan",
                    "2": "Feb",
                    "3": "Mär",
                    "4": "Apr",
                    "5": "Mai",
                    "6": "Jun",
                    "7": "Jul",
                    "8": "Aug",
                    "9": "Sep",
                    "10": "Okt",
                    "11": "Nov",
                    "12": "Dez",
                },
            },
            "seasons": {
                "1": "Winter",
                "2": "Frühling",
                "3": "Sommer",
                "4": "Herbst",
            },
        },
        "fr": {
            "weekdays": {
                "long": {
                    "1": "lundi",
                    "2": "mardi",
                    "3": "mercredi",
                    "4": "jeudi",
                    "5": "vendredi",
                    "6": "samedi",
                    "7": "dimanche",
                },
                "short": {
                    "1": "lun",
                    "2": "mar",
                    "3": "mer",
                    "4": "jeu",
                    "5": "ven",
                    "6": "sam",
                    "7": "dim",
                },
            },
            "months": {
                "long": {
                    "1": "janvier",
                    "2": "février",
                    "3": "mars",
                    "4": "avril",
                    "5": "mai",
                    "6": "juin",
                    "7": "juillet",
                    "8": "août",
                    "9": "septembre",
                    "10": "octobre",
                    "11": "novembre",
                    "12": "décembre",
                },
                "short": {
                    "1": "janv",
                    "2": "févr",
                    "3": "mars",
                    "4": "avr",
                    "5": "mai",
                    "6": "juin",
                    "7": "juil",
                    "8": "août",
                    "9": "sept",
                    "10": "oct",
                    "11": "nov",
                    "12": "déc",
                },
            },
            "seasons": {
                "1": "hiver",
                "2": "printemps",
                "3": "été",
                "4": "automne",
            },
        },
        "es": {
            "weekdays": {
                "long": {
                    "1": "lunes",
                    "2": "martes",
                    "3": "miércoles",
                    "4": "jueves",
                    "5": "viernes",
                    "6": "sábado",
                    "7": "domingo",
                },
                "short": {
                    "1": "lun",
                    "2": "mar",
                    "3": "mié",
                    "4": "jue",
                    "5": "vie",
                    "6": "sáb",
                    "7": "dom",
                },
            },
            "months": {
                "long": {
                    "1": "enero",
                    "2": "febrero",
                    "3": "marzo",
                    "4": "abril",
                    "5": "mayo",
                    "6": "junio",
                    "7": "julio",
                    "8": "agosto",
                    "9": "septiembre",
                    "10": "octubre",
                    "11": "noviembre",
                    "12": "diciembre",
                },
                "short": {
                    "1": "ene",
                    "2": "feb",
                    "3": "mar",
                    "4": "abr",
                    "5": "may",
                    "6": "jun",
                    "7": "jul",
                    "8": "ago",
                    "9": "sept",
                    "10": "oct",
                    "11": "nov",
                    "12": "dic",
                },
            },
            "seasons": {
                "1": "invierno",
                "2": "primavera",
                "3": "verano",
                "4": "otoño",
            },
        },
        "it": {
            "weekdays": {
                "long": {
                    "1": "lunedì",
                    "2": "martedì",
                    "3": "mercoledì",
                    "4": "giovedì",
                    "5": "venerdì",
                    "6": "sabato",
                    "7": "domenica",
                },
                "short": {
                    "1": "lun",
                    "2": "mar",
                    "3": "mer",
                    "4": "gio",
                    "5": "ven",
                    "6": "sab",
                    "7": "dom",
                },
            },
            "months": {
                "long": {
                    "1": "gennaio",
                    "2": "febbraio",
                    "3": "marzo",
                    "4": "aprile",
                    "5": "maggio",
                    "6": "giugno",
                    "7": "luglio",
                    "8": "agosto",
                    "9": "settembre",
                    "10": "ottobre",
                    "11": "novembre",
                    "12": "dicembre",
                },
                "short": {
                    "1": "gen",
                    "2": "feb",
                    "3": "mar",
                    "4": "apr",
                    "5": "mag",
                    "6": "giu",
                    "7": "lug",
                    "8": "ago",
                    "9": "set",
                    "10": "ott",
                    "11": "nov",
                    "12": "dic",
                },
            },
            "seasons": {
                "1": "inverno",
                "2": "primavera",
                "3": "estate",
                "4": "autunno",
            },
        },
        "pt": {
            "weekdays": {
                "long": {
                    "1": "segunda-feira",
                    "2": "terça-feira",
                    "3": "quarta-feira",
                    "4": "quinta-feira",
                    "5": "sexta-feira",
                    "6": "sábado",
                    "7": "domingo",
                },
                "short": {
                    "1": "seg",
                    "2": "ter",
                    "3": "qua",
                    "4": "qui",
                    "5": "sex",
                    "6": "sáb",
                    "7": "dom",
                },
            },
            "months": {
                "long": {
                    "1": "janeiro",
                    "2": "fevereiro",
                    "3": "março",
                    "4": "abril",
                    "5": "maio",
                    "6": "junho",
                    "7": "julho",
                    "8": "agosto",
                    "9": "setembro",
                    "10": "outubro",
                    "11": "novembro",
                    "12": "dezembro",
                },
                "short": {
                    "1": "jan",
                    "2": "fev",
                    "3": "mar",
                    "4": "abr",
                    "5": "mai",
                    "6": "jun",
                    "7": "jul",
                    "8": "ago",
                    "9": "set",
                    "10": "out",
                    "11": "nov",
                    "12": "dez",
                },
            },
            "seasons": {
                "1": "inverno",
                "2": "primavera",
                "3": "verão",
                "4": "outono",
            },
        },
        "pl": {
            "weekdays": {
                "long": {
                    "1": "poniedziałek",
                    "2": "wtorek",
                    "3": "środa",
                    "4": "czwartek",
                    "5": "piątek",
                    "6": "sobota",
                    "7": "niedziela",
                },
                "short": {
                    "1": "pon",
                    "2": "wt",
                    "3": "śr",
                    "4": "czw",
                    "5": "pt",
                    "6": "sob",
                    "7": "niedz",
                },
            },
            "months": {
                "long": {
                    "1": "styczeń",
                    "2": "luty",
                    "3": "marzec",
                    "4": "kwiecień",
                    "5": "maj",
                    "6": "czerwiec",
                    "7": "lipiec",
                    "8": "sierpień",
                    "9": "wrzesień",
                    "10": "październik",
                    "11": "listopad",
                    "12": "grudzień",
                },
                "short": {
                    "1": "sty",
                    "2": "lut",
                    "3": "mar",
                    "4": "kwi",
                    "5": "maj",
                    "6": "cze",
                    "7": "lip",
                    "8": "sie",
                    "9": "wrz",
                    "10": "paź",
                    "11": "lis",
                    "12": "gru",
                },
            },
            "seasons": {
                "1": "zima",
                "2": "wiosna",
                "3": "lato",
                "4": "jesień",
            },
        },
        "da": {
            "weekdays": {
                "long": {
                    "1": "mandag",
                    "2": "tirsdag",
                    "3": "onsdag",
                    "4": "torsdag",
                    "5": "fredag",
                    "6": "lørdag",
                    "7": "søndag",
                },
                "short": {
                    "1": "man",
                    "2": "tir",
                    "3": "ons",
                    "4": "tor",
                    "5": "fre",
                    "6": "lør",
                    "7": "søn",
                },
            },
            "months": {
                "long": {
                    "1": "januar",
                    "2": "februar",
                    "3": "marts",
                    "4": "april",
                    "5": "maj",
                    "6": "juni",
                    "7": "juli",
                    "8": "august",
                    "9": "september",
                    "10": "oktober",
                    "11": "november",
                    "12": "december",
                },
                "short": {
                    "1": "jan",
                    "2": "feb",
                    "3": "mar",
                    "4": "apr",
                    "5": "maj",
                    "6": "jun",
                    "7": "jul",
                    "8": "aug",
                    "9": "sep",
                    "10": "okt",
                    "11": "nov",
                    "12": "dec",
                },
            },
            "seasons": {
                "1": "vinter",
                "2": "forår",
                "3": "sommer",
                "4": "efterår",
            },
        },
        "sv": {
            "weekdays": {
                "long": {
                    "1": "måndag",
                    "2": "tisdag",
                    "3": "onsdag",
                    "4": "torsdag",
                    "5": "fredag",
                    "6": "lördag",
                    "7": "söndag",
                },
                "short": {
                    "1": "mån",
                    "2": "tis",
                    "3": "ons",
                    "4": "tor",
                    "5": "fre",
                    "6": "lör",
                    "7": "sön",
                },
            },
            "months": {
                "long": {
                    "1": "januari",
                    "2": "februari",
                    "3": "mars",
                    "4": "april",
                    "5": "maj",
                    "6": "juni",
                    "7": "juli",
                    "8": "augusti",
                    "9": "september",
                    "10": "oktober",
                    "11": "november",
                    "12": "december",
                },
                "short": {
                    "1": "jan",
                    "2": "feb",
                    "3": "mar",
                    "4": "apr",
                    "5": "maj",
                    "6": "jun",
                    "7": "jul",
                    "8": "aug",
                    "9": "sep",
                    "10": "okt",
                    "11": "nov",
                    "12": "dec",
                },
            },
            "seasons": {
                "1": "vinter",
                "2": "vår",
                "3": "sommar",
                "4": "höst",
            },
        },
        "tr": {
            "weekdays": {
                "long": {
                    "1": "Pazartesi",
                    "2": "Salı",
                    "3": "Çarşamba",
                    "4": "Perşembe",
                    "5": "Cuma",
                    "6": "Cumartesi",
                    "7": "Pazar",
                },
                "short": {
                    "1": "Pzt",
                    "2": "Sal",
                    "3": "Çar",
                    "4": "Per",
                    "5": "Cum",
                    "6": "Cmt",
                    "7": "Paz",
                },
            },
            "months": {
                "long": {
                    "1": "Ocak",
                    "2": "Şubat",
                    "3": "Mart",
                    "4": "Nisan",
                    "5": "Mayıs",
                    "6": "Haziran",
                    "7": "Temmuz",
                    "8": "Ağustos",
                    "9": "Eylül",
                    "10": "Ekim",
                    "11": "Kasım",
                    "12": "Aralık",
                },
                "short": {
                    "1": "Oca",
                    "2": "Şub",
                    "3": "Mar",
                    "4": "Nis",
                    "5": "May",
                    "6": "Haz",
                    "7": "Tem",
                    "8": "Ağu",
                    "9": "Eyl",
                    "10": "Eki",
                    "11": "Kas",
                    "12": "Ara",
                },
            },
            "seasons": {
                "1": "kış",
                "2": "ilkbahar",
                "3": "yaz",
                "4": "sonbahar",
            },
        },
        "cs": {
            "weekdays": {
                "long": {
                    "1": "pondělí",
                    "2": "úterý",
                    "3": "středa",
                    "4": "čtvrtek",
                    "5": "pátek",
                    "6": "sobota",
                    "7": "neděle",
                },
                "short": {
                    "1": "po",
                    "2": "út",
                    "3": "st",
                    "4": "čt",
                    "5": "pá",
                    "6": "so",
                    "7": "ne",
                },
            },
            "months": {
                "long": {
                    "1": "leden",
                    "2": "únor",
                    "3": "březen",
                    "4": "duben",
                    "5": "květen",
                    "6": "červen",
                    "7": "červenec",
                    "8": "srpen",
                    "9": "září",
                    "10": "říjen",
                    "11": "listopad",
                    "12": "prosinec",
                },
                "short": {
                    "1": "led",
                    "2": "úno",
                    "3": "bře",
                    "4": "dub",
                    "5": "kvě",
                    "6": "čer",
                    "7": "čvc",
                    "8": "srp",
                    "9": "zář",
                    "10": "říj",
                    "11": "lis",
                    "12": "pro",
                },
            },
            "seasons": {"1": "zima", "2": "jaro", "3": "léto", "4": "podzim"},
        },
        "fi": {
            "weekdays": {
                "long": {
                    "1": "maanantai",
                    "2": "tiistai",
                    "3": "keskiviikko",
                    "4": "torstai",
                    "5": "perjantai",
                    "6": "lauantai",
                    "7": "sunnuntai",
                },
                "short": {
                    "1": "ma",
                    "2": "ti",
                    "3": "ke",
                    "4": "to",
                    "5": "pe",
                    "6": "la",
                    "7": "su",
                },
            },
            "months": {
                "long": {
                    "1": "tammikuu",
                    "2": "helmikuu",
                    "3": "maaliskuu",
                    "4": "huhtikuu",
                    "5": "toukokuu",
                    "6": "kesäkuu",
                    "7": "heinäkuu",
                    "8": "elokuu",
                    "9": "syyskuu",
                    "10": "lokakuu",
                    "11": "marraskuu",
                    "12": "joulukuu",
                },
                "short": {
                    "1": "tammi",
                    "2": "helmi",
                    "3": "maalis",
                    "4": "huhti",
                    "5": "touko",
                    "6": "kesä",
                    "7": "heinä",
                    "8": "elo",
                    "9": "syys",
                    "10": "loka",
                    "11": "marras",
                    "12": "joulu",
                },
            },
            "seasons": {
                "1": "talvi",
                "2": "kevät",
                "3": "kesä",
                "4": "syksy",
            },
        },
    } %}

    {{ return(datepart_names_by_language[language][datepart]) }}

{% endmacro %}
