# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'airbnb'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'airbnb'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-start:
  - "create table if not exists {{ target.schema }}.audit_log ( model_name string, run_timestamp timestamp )"
models:
  # this `airbnb` usually matches the project `name: airbnb` at the top.
  airbnb:
    +grants:
      select: ["transform", "reporter"]
    +post-hook:
      - "insert into {{ target.schema }}.audit_log values ('{{ this }}', CURRENT_TIMESTAMP)"
    # + means this is an internal keyword for dbt, not a model folder
    +materialized: view
    dim:
      +materialized: table
    src:
      +materialized: ephemeral
    fct:
      +tags: ['fact']
data_tests:
  # you will be able to see test failures, from logs:
  # select * from AIRBNB.DEV_dbt_test__audit.accepted_values_dim_listings_c_85259bd6121f69d13e3814c2538c188d
  +store_failures: true
  # overwrite the default schema used to store test failures, final name is prefixed with dev_, i.e. dev_test_failures_leiw
  +schema: test_failures_leiw
flags:
  #require_generic_test_arguments_property: true
  # there are two other ways:
  # 1. export DBT_ENGINE_FAIL_FAST=true
  # 2. dbt debug (--fail-fast|--no-fail-fast)
  fail_fast: true
vars:
  user_name: default_user_name_for_this_project
